### ISSUE TITLE
Links not displayed when using 6.0.0-rc4

### ISSUE THREAD

**Issue by alindberg** [swimlane/ngx-graph#180] opened 2019-03-19 15:51 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When using ngx-graph 6.0.0-rc4, links are not displayed.  If an object is moved, the link appears but is not attached to any object.

Re-building with 6.0.0-rc3, all is good.

**Expected behavior**
The links should appear and move with the objects

Also note that with 6.0.0-rc3, when an object is moved the links revert to straight lines.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Angular CLI: 7.3.5
Node: 11.10.1
OS: linux x64
Angular: 7.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.4
@angular-devkit/build-angular      0.11.4
@angular-devkit/build-ng-packagr   0.11.4
@angular-devkit/build-optimizer    0.11.4
@angular-devkit/build-webpack      0.11.4
@angular-devkit/core               7.1.4
@angular-devkit/schematics         7.3.5
@angular/cdk                       7.3.4
@angular/cli                       7.3.5
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.1.4
@schematics/angular                7.3.5
@schematics/update                 0.13.5
ng-packagr                         4.7.1
rxjs                               6.4.0
typescript                         3.1.6
webpack                            4.23.1
    

* **ngx-graph version:** x.x.x
$ yarn list --pattern @swimlane
yarn list v1.13.0
├─ @swimlane/ngx-charts@10.1.0
└─ @swimlane/ngx-graph@6.0.0-rc.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Same behavior for both Chrome and Firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS - 3.1.6 ES6

![Snag_a7af2f](https://user-images.githubusercontent.com/9355648/54622368-7c440500-4a37-11e9-8601-1eeffed7332f.png)

![Snag_a7ca48](https://user-images.githubusercontent.com/9355648/54622374-7f3ef580-4a37-11e9-87ab-8b61ca92641f.png)

![Snag_a7d95c](https://user-images.githubusercontent.com/9355648/54622378-81a14f80-4a37-11e9-9d38-c787c3bbf222.png)

![Snag_a7e785](https://user-images.githubusercontent.com/9355648/54622384-8403a980-4a37-11e9-9e88-079727629814.png)

**Comment by DaanTul** [comment] 2019-03-20 12:10
Similar issue here. Getting Nodes and Link Labels but no edges.

**Comment by alindberg** [comment] 2019-04-01 13:33
This issues is not resolved in RC5

**Comment by marjan-georgiev** [comment] 2019-04-01 13:41
@alindberg could you create a stackblitz please? I am not able to reproduce this.

**Comment by alindberg** [comment] 2019-04-03 17:48
I created a [stackblitz](https://stackblitz.com/edit/angular-ngx-graph-linkexample) demonstrating the issues I am having.

If you modify package.json to use <code><strong>@swimlane/ngx-graph@6.0.0-rc.3</strong></code>, then the links will appear as expected.  using <code><strong>rc.4</strong> or <strong>rc.5</strong></code> the links will only appear if a box is moved, and then they are not connected to the objects.

My application builds the directed graph based on a service that fetches data from a DB.  The links show the relationship between objects.

FYI, I could make it work running Firefox, but Chrome and IE/Edge failed to load even the editor..... :-(

Also please note that when the nodes are moved using rc.3, the links revert to straight lines.  This issue was reported fixed this past August.  See "[Curved edges changes to line after dragging a node #78](https://github.com/swimlane/ngx-graph/issues/78)"

**Comment by marjan-georgiev** [comment] 2019-04-03 17:52
Weird, that stackblitz renders fine for me both on Chrome and Firefox. Which version of Chrome are you trying this on?

![image](https://user-images.githubusercontent.com/8687/55501044-e240a700-5649-11e9-9d08-2e94b6961cd4.png)

**Comment by alindberg** [comment] 2019-04-03 17:59
I am using Chrome 72.0.3626.121, Firefox 60.6.1esr (64-bit

**Comment by alindberg** [comment] 2019-04-03 18:22
Let me clarify my comment about working:  Stackblitz does not work for me unless I use Firefox.  The issue reported fails regardless of the browser used.

**Comment by alindberg** [comment] 2019-04-03 18:23
To see the failure reported, change the version of @swimlane/ngx-graph to 6.0.0-rc.4 or rc.5 and rerun.

**Comment by marjan-georgiev** [comment] 2019-04-03 18:54
Ah, I didn't notice the version in stackblitz is rc.3. I can reproduce it now, thank you!

**Comment by marjan-georgiev** [comment] 2019-04-03 19:00
It seems to be caused by the `autoZoom` input. If you remove that it works fine. I am working on a fix.

**Comment by marjan-georgiev** [comment] 2019-04-03 19:25
Released 6.0.0-rc.6. Please let me know if this fixes it.

**Comment by alindberg** [comment] 2019-04-03 19:32
Yep - the links now display.  They still are changing to straight lines when an object is moved, but they are there.

Thanks.

**Comment by marjan-georgiev** [comment] 2019-04-03 19:49
The straight lines are caused by the layout. You can use the `dagreNodesOnly` layout for a small improvement over that, but it has a bit different lines. Nevertheless, that's a different issue. I'm closing this one. Thanks for helping me reproduce!

**Closed by marjan-georgiev** 2019-04-03 19:49 UTC

**Comment by NikitaKasovsky** [comment] 2019-04-09 10:52
Hello. I noticed what `dagreNodesOnly` now not working after init graph component.
