### ISSUE TITLE
Link labels are not getting updated.

### ISSUE THREAD

**Issue by tom-riddle** [swimlane/ngx-graph#121] opened 2018-08-23 22:32 UTC
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
when we dyncamilly update the text of edge labels at run time, it does not gets updated.

**Expected behavior**
Updating the edge label should be reflected on UI

**Reproduction of the problem**
Create a graph with some nodes and edges:

    nodes: [
        {
            id: 'open',
            label: 'open',
            data: {
                id: 'open',
                name: 'open',
                description: 'something',
                actions: ''
            }
        }, {
            id: 'stage1',
            label: 'stage1',
            data: {
                id: 'stage1',
                name: 'stage1',
                description: 'something',
                actions: ''
            }
        }, {
            id: 'stage2',
            label: 'stage2',
            data: {
                id: 'stage2',
                name: 'stage2',
                description: 'something',
                actions: ''
            }
        }
    ],
    links: [{
        source: 'open',
        target: 'stage1',
        label: 'first',
        data: {
            name: 'first',
            description: 'testing',
            actions: []
        }

    }, {
        source: 'open',
        target: 'stage2',
        label: 'second',
        data: {
            name: 'second',
            description: 'testing',
            actions: []
        }

    }]

Template of links:

      <ng-template #linkTemplate let-link>
        <svg:g class="edge" (click)="editTransition(link)">
          <svg:path class="line" stroke-width="2" stroke="#bebebe" stroke-dasharray="2,2" marker-end="url(#arrow)">
          </svg:path>

          <svg:text class="edge-label" text-anchor="middle">
            <textPath class="text-path" [attr.href]="'#' + link.id" style="fill: #4c4c4c;" [style.dominant-baseline]="link.dominantBaseline"
              startOffset="50%">
              {{link.label}}
            </textPath>
          </svg:text>
        </svg:g>
      </ng-template>

Set a click listener for the edge label. Inside the click handler, simply update the 'label' property of the link and refresh the graph with :
this.hierarchyGraph=JSON.parse(JSON.stringify(this.hierarchyGraph));
or 
this.hierarchyGraph['links']=[...this.hierarchyGraph['links']] 

* **ngx-graph version:** x.x.x
5.1.0

* **Angular version:** x.x.x
6.x
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by tom-riddle** [comment] 2018-08-25 22:43
Binding of <textpath> with [attr.href] could be one of the reason for this behavious

**Comment by assafsun** [comment] 2018-12-19 15:10
@tom-riddle the problem is the connection between the links which used as an input binding and the links that are inside the graph.
I have a solution that after changing the link data (label in your case) and calling the update observable, the graph will be update with the link data (today, just calling the update observable will not work).
The problem is that the graph is returned to the original state because it's being created again.

**Comment by assafsun** [comment] 2018-12-29 07:47
Duplicate of #100 
Closing this issue in order to track this issue in #100 

I saw this issue also and will want to fix it.

Thanks.

**Closed by assafsun** 2018-12-29 07:47 UTC
Labels: bug
