### ISSUE TITLE
AutoZoom only working when showMinimap is true

### ISSUE THREAD

**Issue by alkn87** [swimlane/ngx-graph#345] opened 2020-08-27 10:53 UTC
**Describe the bug**
AutoZoom not working with version > 7.0.1 because graphDims are always 0. This leads to zoomLevel 1 due to divison by 0 in zoomToFit(). AutoZoom is only working when showMinimap is enabled because this is the only place that calls updateGraphDims().

**Expected behavior**
AutoZoom should work without having showMinimap set to true.

**ngx-graph version**
above 7.0.1

**Comment by marjan-georgiev** [comment] 2020-09-21 13:28
This is a duplicate of https://github.com/swimlane/ngx-graph/issues/334

**Closed by marjan-georgiev** 2020-09-21 13:28 UTC
Labels: bug
