### ISSUE TITLE
panToNode$ is not working when zoom level is present

### ISSUE THREAD

**Issue by Mandar143** [swimlane/ngx-graph#364] opened 2020-11-27 10:11 UTC
Hi Team,

Can you please provide a solution for this panToNode$.

I have read documentation and every thing.....still its not working..

i have tried using this also
**const node = this.nodes.find(n => n.id === nodeId); to
const node = this.graph.nodes.find(n => n.id === nodeId);**

But still no luck..

I am using dagreNodesOnly.ts Layout from this
https://github.com/swimlane/ngx-graph/tree/master/projects/swimlane/ngx-graph/src/lib/graph/layouts

**Comment by ilannn** [comment] 2021-02-05 07:50
Possible duplicate of https://github.com/swimlane/ngx-graph/issues/358

**Comment by marjan-georgiev** [comment] 2021-02-11 12:01
Closing as duplicate of #358

**Closed** 2021-02-11 12:12 UTC
Labels: duplicate
