### ISSUE TITLE
modification layoutSettings Orient?

### ISSUE THREAD

**Issue by dongjunson** [swimlane/ngx-graph#204] opened 2019-05-30 07:48 UTC
![KakaoTalk_20190530_172240319](https://user-images.githubusercontent.com/32211517/58619288-92a3f200-82ff-11e9-809a-6a6565927c3f.jpg)
how can i change layoutSetting like this?

this is not '**TB**' or '**BT**'

**Comment by assafsun** [comment] 2019-06-07 08:45
Interesting, in case you will use dagre, this is a combination of TB with BT.

**Comment by dongjunson** [comment] 2019-06-10 05:43
> Interesting, in case you will use dagre, this is a combination of TB with BT.
yes. i want to layout of combination, so i'll find the way custom layout.
[https://swimlane.github.io/ngx-graph/#layouts#custom-layouts](https://swimlane.github.io/ngx-graph/#layouts#custom-layouts)

i dont understand '**Instantiate an object from the layout**'??
can i see the example about that?

**Comment by assafsun** [comment] 2019-06-10 05:48
@dongjunson , you can find examples in the documentation of ngx-graph and please look at the input value 'layout' that ngx-graph can get.

Please understand that a custom layout means that you will set your own nodes and edges position and not use dagre which is a common layout engine for settings the nodes and edges.

I don't think you can achieve this layout with dagre but this is something that needs investigation as I see it.

**Comment by dongjunson** [comment] 2019-06-10 06:12
@assafsun i use layout 'dagreCluster'.Change node position,cluster position, but after re-rendering or updating, Nodes,clusters position change initial positions. this meaning first position is located by ngModule files are fixed.um.. i do more invetigate this sources. thanks for comments.

**Comment by assafsun** [comment] 2019-06-14 16:49
I think after adding new nodes (not position changes) the graph is recreated because a new layout is require. the old layout is not save when new nodes are added by design.

Thanks for your comments, I will appreciate your update if you will create a custom layout that support your case as it can contribute for multiple layout that we can achieve.

Closing this issue.

**Closed by assafsun** 2019-06-14 16:49 UTC
Labels: enhancement

**Comment by dongjunson** [comment] 2019-06-27 06:18
![image](https://user-images.githubusercontent.com/32211517/60241315-f95fff80-98ed-11e9-8659-f0adc2f7548a.png)

this issued was closed. i write this case of resolevd way.
first of all, i use layout setting of  'top of bottom'
and i modifiy node ordering darge library source.
edge line curve is used customeCurevd.ts lastest updated filess.
finally. i get reached rhe result.

it is important to understanding darge library ;->; thanks read mt comment;

**Comment by arsh437git** [comment] 2020-07-27 21:10
@dongjunson , Hi I need your help very urgently , I want to group nodes in the respective clusters and the cluster node shold be TB where as the cluster should be horizontally placed ?, how can i ACHIEVE THIS.

![image](https://user-images.githubusercontent.com/37994048/88592461-aec62f00-d07b-11ea-832a-158458917b9c.png)
