### ISSUE TITLE
Do we support multiple (more than two) links between two nodes?

### ISSUE THREAD

**Issue by rahul-winner** [swimlane/ngx-graph#152] opened 2019-01-18 10:29 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
We are using ngx-graph for rendering quite complex graph and we have few situations where one could have multiple links between two nodes. I noticed ngx-graph is not rendering it. Not sure if this is a bug or require some enhancement.

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
We are using NPM

* **ngx-graph version:** 
5.3.0

* **Angular version:** x.x.x

7.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by assafsun** [comment] 2019-01-20 04:41
Thanks.
I would like to verify that the you are using ngx-grpah 5.3.0, is that right?

In addition, can you please add screen shots or more explanation on what is not rendered?  The topic is too general :)

**Comment by rahul-winner** [comment] 2019-01-20 06:48
@assafsun yes, we are using ngx-graph 5.3.0.

Here is a picture demonstrating the issue I'm talking about. Multiple links are drawn between 'get_ioc_tc' and 'render_message' nodes. We also have same requirement where one node can be linked by other node with different types of associations. 

I hope it is helpful.

![image](https://user-images.githubusercontent.com/4982751/51436137-17756400-1cad-11e9-8fcc-5d367b826723.png)

**Comment by rahul-winner** [comment] 2019-01-25 08:52
@assafsun did you get a chance to look at this? Is it really supported or not? 

Thank you.

**Comment by assafsun** [comment] 2019-01-25 17:42
@rahul-winner, Please give me your comments on the issues below.

1. I don't know how ngx-graph acts with multiple links, interesting to know.
Until now, I didn't tested it or saw it.
2. In case you added multiple links to the demo app code, the lines shapes that you marked are the result of the bundle curve from d3 (I don't see a problem with it).
3. On onthe one hand, you wrote that your graph is complex with multiple links between nodes but ngx graph don't render it on the other hand, the image shows that multiple links are drawn.
Is the problem the different link UI which looks different between **get_ioc_tc** and **render_message** or multiple links appears without asking for it?
If it's the UI problem which results in consistent links then I don't think we can fix it in ngx-graph but I have a few suggestions for a solution.

Thanks! Hope that I will help.

**Comment by rahul-winner** [comment] 2019-01-25 19:05
Thank you @assafsun for your help.

I am not able to render multiple links in any way using ngx-graph. 
In order to demonstrate the requirement, I simply captured the screenshot of demo page, edited it and drawn more arrows using paint-brush. I hope it clarifies most of the confusion.

It will be a great help if you could help me in figuring out solution for this. Kindly let me know if further elaboration needed to understand it better.

Regards.

**Comment by assafsun** [comment] 2019-01-26 10:17
Sorry for the confusion :)

Try to set multiple links in the links configuration which you pass to ngx-graph.
It's interesting to see if dagre layout sets points and links for each multiple links or we need to change something in the dagre layout properties.

If we will have an option using dagre to support it, then let's add it.
Otherwise, in case dagre don't support multiple links between the same nodes, my recommendation will be to wait for version 6 and set you own layout which will support it.

As mentioned in another issue, I'm a little bit busy with other issues but available for questions etc - I will be able to look at it maybe next week and understand if dagre can support it.
You can start the investigation yourself and we can sync on your results to understand the best solution.

In addition, regardless to this issue, I will be happy to see your graph use with ngx-graph and how your complex graph looks.

**Comment by assafsun** [comment] 2019-01-30 17:13
@rahul-winner 
Update: Thanks to @marjan-georgiev, ngx-graph will support multiple links between node.
Hope to issue a PR this week or early next week.

**Comment by assafsun** [comment] 2019-01-31 08:14
https://github.com/swimlane/ngx-graph/pull/159

**Comment by assafsun** [comment] 2019-02-07 07:35
Closing this.

1. We pushed support for it
2. Duplicate of https://github.com/swimlane/ngx-graph/issues/123 which can be monitor there

**Closed by assafsun** 2019-02-07 07:35 UTC
