### ISSUE TITLE
Updating graph from UI

### ISSUE THREAD

**Issue by Githamza** [swimlane/ngx-graph#246] opened 2019-09-09 22:38 UTC
**Is your feature request related to a problem? Please describe.**
I'm trying to create a workflow editor, so I would use ngx-graph library. I don't see how to draw relations between nodes using mouse.
**Describe the solution you'd like**
I would like to be able to connect or disconnect nodes directly from UI
**Describe alternatives you've considered**
Here an example
https://rete.js.org/#/examples/basic

Using rete library

https://github.com/retejs/rete

**Comment by assafsun** [comment] 2019-09-29 12:09
Thanks for this suggestion, ngx-graph currently is not supporting this use case directly.
This is duplicate of https://github.com/swimlane/ngx-graph/issues/62 where you can find there more information.

I think @marjan-georgiev implemented a similar use case that may help you

Closing it for now, let me know if I missed something

**Closed by assafsun** 2019-09-29 12:09 UTC
Labels: enhancement
