### ISSUE TITLE
Save position and use icon instead of boxes

### ISSUE THREAD

**Issue by calebeaires** [swimlane/ngx-graph#19] opened 2017-07-26 14:13 UTC
First, thanks to this great angular component! 👍 

[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here

1. Save position;
2. Change nodes styles like set icon to it;

Would be great if ngx-charts-dag could have more control on nodes. Tools like control/save position and change nodes styles. I have one app that uses js.cytoscape to make tasks workflow, but I am thinking on other (simple) lib to handle ngx-charts-dag fits to this need. Here is the flow I would like to use with ngx-charts-dag

<img width="1379" alt="screen shot 2017-07-26 at 10 50 32" src="https://user-images.githubusercontent.com/794195/28625334-4651c028-71f2-11e7-8e34-f4b75adafeda.png">
 
Since we already use ngx-charts on this app, the same tool familly ngx-charts-dag will be a great choise. **So, does ngx-charts-dag has some roadmap to implement saving position and change node style?**

1. Angular CLI 1.2
2. Angular 4

**Comment by marjan-georgiev** [comment] 2017-07-26 14:17
We already support full customization of node and link styles by using ng-templates. You can completely customize how your nodes look. This is an example from the demo page:

https://github.com/swimlane/ngx-charts-dag/blob/master/demo/app.component.html#L22

We plan on supporting fixed position of nodes. It will be added in an upcoming version.

**Comment by Hypercubed** [comment] 2017-08-18 23:40
Duplicate of #2

**Comment by kenisteward** [comment] 2017-12-07 15:45
Should this be closed?

**Comment by isaacplmann** [comment] 2017-12-13 18:27
Closing.  Styling of nodes can be done with `ng-template`s and repositioning is being tracked by #2.

**Closed by isaacplmann** 2017-12-13 18:27 UTC
