### ISSUE TITLE
Link label visible only with chrome

### ISSUE THREAD

**Issue by daniel-luna-gonzalez** [swimlane/ngx-graph#176] opened 2019-03-14 00:02 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Label text not visible with Firefox and Safari only works in Chrome

**Expected behavior**
Label text must be visible in firefox, safari and chrome
**Reproduction of the problem**
https://stackblitz.com/edit/ngx-graph-simple-example

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

{
"name": "control-gestion-front",
"version": "0.0.0",
"scripts": {
"ng": "ng",
"start": "ng serve",
"build": "ng build",
"test": "ng test",
"lint": "ng lint",
"e2e": "ng e2e"
},
"private": true,
"dependencies": {
"@angular/animations": "^6.1.6",
"@angular/cdk": "^6.4.7",
"@angular/common": "^6.1.0",
"@angular/compiler": "^6.1.0",
"@angular/core": "^6.1.0",
"@angular/forms": "^6.1.0",
"@angular/http": "^6.1.0",
"@angular/material": "^6.4.7",
"@angular/material-moment-adapter": "^7.0.2",
"@angular/platform-browser": "^6.1.0",
"@angular/platform-browser-dynamic": "^6.1.0",
"@angular/router": "^6.1.0",
"@fortawesome/angular-fontawesome": "^0.2.0",
"@fortawesome/fontawesome-svg-core": "^1.2.4",
"@fortawesome/free-solid-svg-icons": "^5.3.1",
"@ng-bootstrap/ng-bootstrap": "^3.2.0",
"@swimlane/ngx-charts": "^10.0.0",
"@swimlane/ngx-graph": "^5.4.1",
"angular-notifier": "^4.1.1",
"angular-tree-component": "^8.0.0",
"core-js": "^2.5.4",
"d3": "^5.8.2",
"d3-shape": "^1.3.4",
"hammerjs": "^2.0.8",
"jquery": "^3.3.1",
"moment": "^2.22.2",
"ng2-pdf-viewer": "^5.2.3",
"rxjs": "^6.0.0",
"web-animations-js": "^2.3.1",
"zone.js": "~0.8.26"
},
"devDependencies": {
"@angular-devkit/build-angular": "^0.7.5",
"@angular/cli": "~6.1.3",
"@angular/compiler-cli": "^6.1.0",
"@angular/language-service": "^6.1.0",
"@types/jasmine": "~2.8.6",
"@types/jasminewd2": "~2.0.3",
"@types/node": "~8.9.4",
"codelyzer": "~4.2.1",
"jasmine-core": "~2.99.1",
"jasmine-spec-reporter": "~4.2.1",
"karma": "^3.0.0",
"karma-chrome-launcher": "~2.2.0",
"karma-coverage-istanbul-reporter": "~2.0.0",
"karma-jasmine": "~1.1.1",
"karma-jasmine-html-reporter": "^0.2.2",
"protractor": "^5.4.0",
"ts-node": "~5.0.1",
"tslint": "~5.9.1",
"typescript": "~2.7.2"
}
}

* **ngx-graph version:** x.x.x
5.4.1
* **Angular version:** x.x.x
Angular 6
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Firefox and Safari
![Greenshot 2019-03-14 09 02 10](https://user-images.githubusercontent.com/13126516/54367389-e6c00400-4637-11e9-8dd8-5e5680f2987a.png)

**Comment by sw2go** [comment] 2019-03-14 15:39
I have the same issue. Labels of Links are displayed in Chrome and Edge but not in Firefox. See https://github.com/sw2go/nodelink it uses current swimlane/ngx-graph.

**Comment by sw2go** [comment] 2019-03-25 10:05
I discovered that the problem with missing Link-Labels ( only in Firefox ) are caused by the [attr.href]="'#' + link.id" within the textPath element in the linkTemplate. If the pages url is the root ( "/" ) Firefox handles the href correctly. If the pages url isn't the root but let's say "/nodes" then href=#id fails in Firefox ( but works in Chrome ). If you put href=nodes#id it works in both.

**Comment by assafsun** [comment] 2019-04-17 17:59
@daniel-luna-gonzalez is this issue still active?

**Comment by daniel-luna-gonzalez** [comment] 2019-04-17 19:15
> @daniel-luna-gonzalez is this issue still active?

Yes @assafsun the issue is still happen

**Comment by KingDarBoja** [comment] 2019-05-12 14:28
@daniel-luna-gonzalez Can you update the library to the latest release and see if it is still bugged? I forked and updated the provided stackblitz and tested it on Firefox (Quantum - 66.0.5 x64) and the labels are visible.

[Stackblitz forked demo](https://stackblitz.com/edit/ngx-graph-simple-example-obxsyy)

**Comment by daniel-luna-gonzalez** [comment] 2019-05-16 00:45
Hi @KingDarBoja I have updated my package.json as follows:

> {
  "name": "control-gestion-front",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.6",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/material": "^6.4.7",
    "@angular/material-moment-adapter": "^7.0.2",
    "@angular/platform-browser": "6.1.10",
    "@angular/platform-browser-dynamic": "6.1.10",
    "@angular/router": "^6.1.0",
    "@fortawesome/angular-fontawesome": "^0.2.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.4",
    "@fortawesome/free-solid-svg-icons": "^5.3.1",
    "@ng-bootstrap/ng-bootstrap": "^3.2.0",
    "@ngrx/store": "^6.0.1",
    "@ngrx/store-devtools": "^6.0.1",
    "@swimlane/ngx-graph": "^6.0.1",
    "@swimlane/ngx-charts": "11.1.0",
    "angular-notifier": "^4.1.1",
    "angular-tree-component": "^8.0.0",
    "core-js": "^2.5.4",
    "d3": "^5.8.2",
    "d3-shape": "^1.3.4",
    "hammerjs": "^2.0.8",
    "jquery": "^3.3.1",
    "moment": "^2.22.2",
    "ng2-pdf-viewer": "^5.2.3",
    "rxjs": "6.1.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "~0.8.26",
    "rxjs-compat": "^6.5.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.7.5",
    "@angular/cli": "~6.1.3",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ngrx-store-freeze": "^0.2.4",
    "protractor": "^5.4.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
}


After run my project with the production flag

> ng serve --prod

I have received the below error

<img width="445" alt="image" src="https://user-images.githubusercontent.com/13126516/57818503-ba188d80-7749-11e9-9088-94ca8c41ce39.png">

I hope you can help me please.

**Comment by KingDarBoja** [comment] 2019-05-17 13:21
Hard to tell what is going wrong on your code since there isn't any code to look at. The screenshot error could be related to anything on your app so I suggest comment out the ngx-graph component where it is being used and check if it isn't related to it.

Also try to share some stackblitz to reproduce the error.

**Comment by assafsun** [comment] 2019-06-14 16:32
Any update on this issue?

**Comment by marjan-georgiev** [comment] 2019-06-26 21:57
Closing this as we can not reproduce. If you still see it happen, please create a stackblitz where the issue can be reproduced and share it with us.

**Closed by marjan-georgiev** 2019-06-26 21:57 UTC
Labels: bug
