### ISSUE TITLE
After building app with ngx-graph for Prod environment tooltip breaks the app.

### ISSUE THREAD

**Issue by Maciejszuchta** [swimlane/ngx-graph#105] opened 2018-07-24 08:55 UTC
Od Dev environtmnt everything works fine. But when i build the app with:

`ng build --prod` my console is filled with errors and page frezzes.

![image](https://user-images.githubusercontent.com/12434636/43127367-9b151fc8-8f2f-11e8-947c-a878352d63ba.png)

I tried to remove tooltips from my html graph template but this doesn't help. Updated my ngx-graph and ngx-charts to the latest version and the error still occurs.

**Comment by sonja1995** [comment] 2018-08-03 12:13
Same issue here. I use the library in my master-thesis-project, but I was able to reproduce the error in a simple setting. Create a new app and inside a new module. Use the ngx-graphs library inside. Build it with the --prod flag. This gives me the error a cryptic error (because of the minifying), which I expect to be the same as the error above.

![error](https://user-images.githubusercontent.com/42065825/43641827-600aa698-9725-11e8-9be5-fe00af14f889.png)

Unfortunatly, I was not able to run the project on stackblitz,  but you may find my reproduction-project with all the informations here: https://stackblitz.com/edit/angular-aacgzq

Thanks for your support!

**Comment by Maciejszuchta** [comment] 2018-08-21 11:25
Thank you, I will also try this and let you know if it worked for me.

**Comment by rikup88** [comment] 2018-08-24 13:01
Same here. Ngx-graph broke after updating Angular from 5 to 6. I will probably try solution suggested above but it really is a hack and this should be fixed.

**Comment by Australhawk** [comment] 2018-08-30 22:06
Just happend this to me. =/

**Comment by Maciejszuchta** [comment] 2018-09-19 11:54
> Same here. Ngx-graph broke after updating Angular from 5 to 6. I will probably try solution suggested above but it really is a hack and this should be fixed.

Did you succeed to use the workaround?

**Comment by nwkyom** [comment] 2018-09-25 12:31
Same here ! And the workaround is not even tryable for our production environment ... Could you plz fix this !!

**Comment by rmiller-sgntr** [comment] 2018-10-16 23:44
This issue is solved for me when removing `aot` from build. I wander if [the answer here](https://github.com/ngrx/platform/issues/549#issuecomment-344515326) can resolve this case as well.

**Comment by Maciejszuchta** [comment] 2018-10-17 07:42
> I ran into this issue as well. This issue is resolved for me when removing `aot` from build. It is a better workaround than the hack suggested above, but not a desired one. I wander if [the answer here](https://github.com/ngrx/platform/issues/549#issuecomment-344515326) can resolve this case as well.

Building without `aot` fixed this issue, graph seems to work fine, thanks :)

**Comment by rferg** [comment] 2018-12-12 16:16
Since the TooltipService and InjectionService are from the dependency [ngx-charts](https://github.com/swimlane/ngx-charts) and not in ngx-graph itself, I looked over there to search for related issues.  I found [#975](https://github.com/swimlane/ngx-charts/issues/975).

The only feasible solution proposed seemed to be [here](https://github.com/swimlane/ngx-charts/issues/975#issuecomment-432603138), which is just to revert to earlier versions of ngx-graph and ngx-charts.  The versions suggested are:
> "@swimlane/ngx-graph": "4.1.1",
> "@swimlane/ngx-charts": "7.3.0"

However, in my case, this was throwing an error because the BaseChartComponent in this old version of ngx-charts was using `Observable.fromEvent` (I'm using Angular v7 and rxjs v6.3).

I changed to **ngx-graph v5.0.0 and ngx-charts v8.1.0** and it worked in production with AOT.  So for those who cannot remove `aot` or `build-optimizer`, this may be an option.

**Comment by SamindaK** [comment] 2018-12-13 04:50
Thanks 

> Since the TooltipService and InjectionService are from the dependency [ngx-charts](https://github.com/swimlane/ngx-charts) and not in ngx-graph itself, I looked over there to search for related issues. I found [#975](https://github.com/swimlane/ngx-charts/issues/975).
> 
> The only feasible solution proposed seemed to be [here](https://github.com/swimlane/ngx-charts/issues/975#issuecomment-432603138), which is just to revert to earlier versions of ngx-graph and ngx-charts. The versions suggested are:
> 
> > "@swimlane/ngx-graph": "4.1.1",
> > "@swimlane/ngx-charts": "7.3.0"
> 
> However, in my case, this was throwing an error because the BaseChartComponent in this old version of ngx-charts was using `Observable.fromEvent` (I'm using Angular v7 and rxjs v6.3).
> 
> I changed to **ngx-graph v5.0.0 and ngx-charts v8.1.0** and it worked in production with AOT. So for those who cannot remove `aot` or `build-optimizer`, this may be an option.

Thanks a lot, it works in Angular 6 as well.

**Comment by assafsun** [comment] 2018-12-29 07:43
Closing this issue as a solution was proposed.
Please update this thread if it's relevant to the latest version 5.2.1

Thanks.

**Closed by assafsun** 2018-12-29 07:43 UTC

**Comment by daniel-luna-gonzalez** [comment] 2019-04-29 21:38
> #975

Thanks, it works me with Angular 6

**Comment by agusdutra** [comment] 2019-06-12 17:04
@assafsun I'm sorry but downgrading the version doesn't seem like a valid solution. 

With the following versions: 

```
    "@swimlane/ngx-charts": "^11.1.0",
    "@swimlane/ngx-graph": "^6.0.1",
```
I'm facing this issue and i can't downgrade. 
Is there a way to inject those services on the application side?

**Comment by KingDarBoja** [comment] 2019-06-14 14:43
@agusdutra Downgrading to `"@swimlane/ngx-charts": "^10.1.0" will do the trick without downgrading the `ngx-graph` package.

I am working on a fix for this issue but still testing it.

Cheers!

**Comment by agusdutra** [comment] 2019-06-17 18:14
@KingDarBoja nice, thanks! will try that and wait for the new version
