### ISSUE TITLE
PanOffSet not working anymore

### ISSUE THREAD

**Issue by simvn** [swimlane/ngx-graph#228] opened 2019-07-24 15:31 UTC
**Describe the bug**
I design control elements in which the user can move my graph using arrow keys. In an earlier version I could move the graph by adding/subtracting values from the current panOffsetY & panOffsetX.
However, after upgrading to v. 6.1.0 setting panOffsetX & Y does not change the position anymore. 

**To Reproduce**

`<ngx-graph #graphWrapper 
          [nodes]="hierarchicalGraph.nodes" 
          [links]="hierarchicalGraph.links" 
          [panOffsetY]="panOffsetY"
          [panOffsetX]="panOffsetX"
          [zoomLevel]="zoom"
          [curve]="curve"
          [view]=""
          [layoutSettings]="layoutSettings"
          [scheme]="colorScheme"
          >
... 
</ngx-graph>`

`@ViewChild('graphWrapper') el: NgxGraphInterface;`

`move(y, x) {
    this.panOffsetX = this.el.panOffsetX + x;
    this.panOffsetY = this.el.panOffsetY + y;
  }`

**Expected behavior**
panOffsetX & panOffsetY should update the position of the graph again.

**ngx-graph version**
v. 6.1.0

Thanks.

**Comment by KingDarBoja** [comment] 2019-08-28 23:39
Hello @simvn 

You can check my working [stackblitz demo](https://stackblitz.com/edit/ngx-graph-kdb-sample?file=app/app.component.ts) and press the arrow keys to see the panning feature working as you request. There is no need to use `panOffsetX` / `panOffsetY` to accomplish what you want.

Cheers!

**Comment by simvn** [comment] 2019-08-29 06:57
Thanks @KingDarBoja  for looking into it!

**Comment by KingDarBoja** [comment] 2019-08-31 17:19
@simvn I have found the issue as stated on my previous commit but also haven't found a proper way of fixing it with the current input parameters.

Each pan offset input uses *setter* and *getters* and be aware that each setter makes a call to the `panTo(x, y)` method which doesn't not handle null `x` or `y` values.
I managed to fix it for each case (x - number | null and y - number | null) to check what is going on but unfortunately, found the setter method isn't being triggered after the first change cycle.

Will keep looking on a fix, probably gonna merge both offset into an array to properly run change detection cycles.

@marjan-georgiev Any thoughts about this issue and my findings?

**Comment by assafsun** [comment] 2020-01-04 15:57
Hi,

1. I think that keyboard navigation is something that should come from ngx-graph.
I started to work on this and hope to release a PR soon.

2. Regrading the pan value, is it related to the pan to node functionality?

**Comment by KingDarBoja** [comment] 2020-01-04 16:26
@assafsun that sounds great! Being able to use the keyboard navigation instead of letting users do it is way better. My PR already provides some slighty changes to the pan offset inputs so maybe those could help you on your work.

Cheers!

**Comment by assafsun** [comment] 2020-01-04 17:11
@KingDarBoja please check and test https://github.com/swimlane/ngx-graph/pull/278

**Comment by assafsun** [comment] 2020-02-15 12:51
Pan to node will be fixed in https://github.com/swimlane/ngx-graph/pull/288
Keyboard navigation still in progress. 
I'm closing this thread as the pan to node will be tracked from another thread

**Closed by assafsun** 2020-02-15 12:51 UTC
Labels: bug

**Comment by baltie** [comment] 2020-07-08 12:55
Would just like to mention that using the panOffsetX and panOffsetY inputs doesn't work in version 7.0.1, not sure why this issue was closed, @assafsun ? panToNode$ works now, but it is not possible to use panOffsetX and panOffsetY to manually control the panning. In my case, I wish to take control of the panOffsetY value so that I can avoid having whitespace at the top of the view box. This to satisfy the UX designer.. panToNode$ will center the graph on the node in both directions, which is often but not always, what I want.

To work around this, I get the GraphComponent as a view child and call panTo() myself, but I would rather not do that as it feels like digging at the internals and could break in the next release of ngx-graph, for all I know.

It seems to me that the problem is the same as before. panOffsetY calls panTo() with x as null. In panTo(), if x is null, it does nothing.

**Comment by Wu-Li** [comment] 2024-01-18 20:38
I'm still experiencing this issue in 8.2.3.

**Comment by ClearConnect** [comment] 2024-12-06 15:42
@baltie would you mind posting the code of getting GraphComponent as a view child and call panTo()  (I'm new to ng ) thanks a lot!
