### ISSUE TITLE
Performance degradation when Link and Node values are returned from method

### ISSUE THREAD

**Issue by rbwrightjr91** [swimlane/ngx-graph#233] opened 2019-08-01 16:52 UTC
**Describe the bug**
Using the quickstart example, I moved the `links` and `nodes` arrays to a method inside the respective `component.ts`. This results in severe performance issues and the graph displaying a single black node.

**To Reproduce**
```
<!-- app.component.html -->

<ngx-graph class="chart-container"
  [view]="[500, 200]"
  [links]="createLinks()"
  [nodes]="createNodes()"></ngx-graph>
```

```
//app.component.ts

import { Component, OnInit, Input } from '@angular/core';
import { Edge, Node } from '@swimlane/ngx-graph';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  constructor() { }

  ngOnInit() {
    
  }

  createLinks() : Edge[] {
    return ([
      {
        id: 'a',
        source: 'first',
      target: 'second',
        label: 'is parent of'
      }, {
        id: 'b',
        source: 'first',
        target: 'third',
        label: 'custom label'
      }
    ]);
  }

  createNodes() : Node[] {
    return ([
      {
        id: 'first',
        label: 'A'
      }, {
        id: 'second',
        label: 'B'
      }, {
        id: 'third',
        label: 'C'
      }
    ]);
  }

}
```

**Expected behavior**
Should behave normally.

**Demo**
https://angular-vj2vkn.stackblitz.io

**ngx-graph version**
`"@swimlane/ngx-graph": "^6.1.0"`

**Comment by KingDarBoja** [comment] 2019-08-02 00:46
I can confirm such behaviour after testing on my own stackblitz. Looks like both function are being called multiple times due to Angular change detection cycles. Even switching to `ChangeDetectionStrategy.OnPush` doesn't work. So I do recommend **passing an Array property** instead of a function call so it will work as expected.

Cheers!

**Comment by rbwrightjr91** [comment] 2019-08-02 16:50
Yeah, that works. Calling the methods in `ngOnInit` and assigning the return to an `Edge[]`/`Link[]` and using those in the HTML solves the issue. Thanks!

**Comment by KingDarBoja** [comment] 2019-08-02 21:56
You're welcome @rbwrightjr91 

@marjan-georgiev Should we close this issue or do you want to take a look at this?

**Comment by marjan-georgiev** [comment] 2019-08-02 21:58
Yes, passing functions inside your templates will cause them to be executed on every change detection cycle. You should cache the result in a property, as @KingDarBoja suggested.

**Closed by marjan-georgiev** 2019-08-02 21:58 UTC
Labels: bug
